Repository stolostron/multicloud-operators-placementrule, pull requests merged in 2019-10, with the labels that each got.

#1 Add myself to owners.
  OWNERS
Labels: approved, lgtm, size/XS

#2 initial check in. removed some policy and status from original feature
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  Makefile
  OWNERS
  README.md
  RELEASE.md
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  cmd/manager/main.go
  cmd/manager/options.go
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
  common/scripts/config_docker.sh
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  deploy/crds/app_v1alpha1_placementrule_cr.yaml
  deploy/crds/app_v1alpha1_placementrule_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  docs/development.md
  go.mod
  go.sum
  hack/boilerplate.go.txt
  hack/test/crds/cluster-registry-crd.yaml
  pkg/apis/addtoscheme_app_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/app/group.go
  pkg/apis/app/v1alpha1/doc.go
  pkg/apis/app/v1alpha1/placementrule_types.go
  pkg/apis/app/v1alpha1/register.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_placementrule.go
  pkg/controller/controller.go
  pkg/controller/placementrule/placement.go
  pkg/controller/placementrule/placementrule_controller.go
  pkg/controller/placementrule/placementrule_controller_suite_test.go
  pkg/controller/placementrule/placementrule_controller_test.go
  pkg/utils/cluster.go
  pkg/utils/kubernetes.go
  pkg/utils/template.go
  pkg/utils/trace.go
  tools.go
  version/version.go
Labels: approved, size/XXL

#3 provide centralized cluster placement functions
  .travis.yml
  Dockerfile
  Makefile
  README.md
  cmd/manager/exec/manager.go
  cmd/manager/exec/options.go
  cmd/manager/main.go
  cmd/manager/options.go
  common/Makefile.common.mk
  common/config/.golangci.yml
  deploy/crds/app_v1alpha1_placementrule_crd.yaml
  go.mod
  go.sum
  pkg/apis/app/v1alpha1/placementrule_types.go
  pkg/apis/app/v1alpha1/placementrule_types_test.go
  pkg/apis/app/v1alpha1/v1alpha1_suite_test.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/placementrule/placement.go
  pkg/controller/placementrule/placementrule_controller_test.go
  pkg/utils/cluster.go
  pkg/utils/eventlog.go
  pkg/utils/kubernetes.go
  pkg/utils/placement.go
  pkg/utils/trace.go
  version/version.go
Labels: approved, lgtm, size/XXL

#4 remove test dependency in build
  Makefile
Labels: approved, lgtm, size/XS

#5 add doc badge and fix lint issues
  Makefile
  README.md
  cmd/manager/exec/manager.go
  cmd/manager/main.go
  pkg/apis/app/v1alpha1/placementrule_types_test.go
  pkg/apis/app/v1alpha1/v1alpha1_suite_test.go
  pkg/controller/controller.go
  pkg/controller/placementrule/placement.go
  pkg/controller/placementrule/placementrule_controller.go
  pkg/controller/placementrule/placementrule_controller_suite_test.go
  pkg/controller/placementrule/placementrule_controller_test.go
  pkg/utils/cluster.go
  pkg/utils/eventlog.go
  pkg/utils/kubernetes.go
  pkg/utils/placement.go
Labels: approved, lgtm, size/M

#6 addd local to placement
  Makefile
  README.md
  common/scripts/codecov.sh
  go.mod
  go.sum
  pkg/apis/app/v1alpha1/placementrule_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/utils/eventlog.go
Labels: approved, lgtm, size/L

#7 Local
  Dockerfile
  Makefile
  README.md
  build/Dockerfile
  common/config/.hadolint.yml
  common/scripts/codecov.sh
  common/scripts/install-operator-sdk.sh
  deploy/crds/app_v1alpha1_placementrule_cr.yaml
  pkg/utils/placement.go
  pkg/utils/utils_suite_test.go
  pkg/utils/utils_test.go
Labels: approved, lgtm, size/L

#8 Cont
  .github/dco.yml
  CONTRIBUTING.md
  Makefile
  common/scripts/codecov.sh
Labels: approved, lgtm, size/S
