Repository stolostron/multicloud-operators-placementrule, pull requests merged in 2021-05, with the labels that each got.

#90 enable metric sorting
  pkg/controller/placementrule/placement.go
  pkg/controller/placementrule/placementrule_controller_test.go
Labels: approved, dco-signoff: yes, lgtm

#85 do not default to amd64 if GOARCH is not set
  common/scripts/gobuild.sh
Labels: approved, dco-signoff: yes, lgtm

#91 Placement performance enhacement
  cmd/manager/exec/manager.go
  pkg/controller/placementrule/placement.go
  pkg/controller/placementrule/placementrule_controller.go
  pkg/utils/auth.go
  pkg/utils/placement.go
Labels: approved, dco-signoff: yes

#94 Change spec to required
  deploy/crds/apps.open-cluster-management.io_placementrules_crd.yaml
  pkg/apis/apps/v1/placementrule_types.go
Labels: approved, dco-signoff: yes, lgtm

#92 Registering managed clusters to multiple argo instances
  Makefile
  Makefile.prow
  build/Dockerfile
  build/Dockerfile.prow
  cmd/gitopscluster/exec/manager.go
  cmd/gitopscluster/exec/options.go
  cmd/gitopscluster/main.go
  deploy/crds/apps.open-cluster-management.io_gitopsclusters.yaml
  go.mod
  go.sum
  hack/test/crds/clusters.open-cluster-management.io_placementdecisions.crd.yaml
  hack/test/crds/clusters.open-cluster-management.io_placements.crd.yaml
  pkg/apis/apps/v1alpha1/gitopscluster_types.go
  pkg/controller/add_gitopscluster.go
  pkg/controller/argocdcluster/argocdcluster.go
  pkg/controller/argocdcluster/argocdcluster_controller.go
  pkg/controller/controller.go
  pkg/controller/gitopscluster/gitopscluster_controller.go
  pkg/controller/gitopscluster/gitopscluster_controller_suite_test.go
  pkg/controller/gitopscluster/gitopscluster_controller_test.go
  pkg/utils/cluster.go
Labels: approved, dco-signoff: no, lgtm

#95 remove old argocd controller
  Makefile
  Makefile.prow
  build/Dockerfile
  build/Dockerfile.prow
  cmd/argocdcluster/exec/manager.go
  cmd/argocdcluster/exec/options.go
  cmd/argocdcluster/main.go
  go.mod
  go.sum
  pkg/controller/add_argocdcluster.go
  pkg/controller/argocdcluster/argocd_controller_test.go
  pkg/controller/argocdcluster/argocdcluster.go
  pkg/controller/argocdcluster/argocdcluster_controller.go
  pkg/controller/argocdcluster/argocdcluster_controller_suite_test.go
  pkg/controller/controller.go
  pkg/controller/gitopscluster/gitopscluster_controller_test.go
Labels: approved, dco-signoff: yes, lgtm
