Repository stolostron/multicloud-operators-placementrule, pull requests merged in 2021-04, with the labels that each got.

#78 add cluster name and URL labels
  go.mod
  go.sum
  pkg/controller/argocdcluster/argocdcluster.go
  pkg/utils/label.go
Labels: approved

#79 CVE-2020-14040 fix - golang.org/x/text
  go.mod
  go.sum
Labels: approved, lgtm

#81 update prow docker base image
  build/Dockerfile.prow
Labels: approved, dco-signoff: yes, lgtm

#82 Rename multiclusterimport to gitopscluster
  deploy/crds/apps.open-cluster-management.io_gitopsclusters.yaml
  pkg/apis/apps/v1alpha1/gitopscluster_types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/gitopscluster/gitopscluster_controller.go
Labels: approved, dco-signoff: no, lgtm

#83 limit access to managed clusters by reviewing the managedclusters get…
  pkg/utils/auth.go
Labels: approved, dco-signoff: yes

#84 add release main branch
  RELEASE_MAIN_BRANCH
Labels: approved, dco-signoff: yes, lgtm

#86 use go 16
  build/Dockerfile.prow
  go.mod
Labels: approved, dco-signoff: yes, lgtm

#88 Add placement examples
  examples/e2e_example/select_cluster_all_e2e.yaml
  examples/e2e_example/select_cluster_by_label_e2e.yaml
  examples/e2e_example/select_cluster_condition_all_avail_e2e.yaml
Labels: approved, dco-signoff: yes, lgtm

#89 remove codecov
  Makefile
  common/scripts/codecov.sh
Labels: approved, dco-signoff: yes, lgtm
